"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$character"""
add_newline = false

[line_break]
disabled = false

[character]
format = ' [→ ](#ffa656)'

[git_branch]
format = '[<$branch(:$remote_branch)>](#ff7b72)'

[directory]
format = '[$path](#79c0ff)[$read_only]($read_only_style) '